# GitHub Actions for AudioKit Cookbook
name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.3

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['12.2']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out AudioKit Cookbook
        uses: actions/checkout@v2
      - name: Build AudioKit Cookbook
        run: |
          set -euo pipefail
          swift package clean
          swift build --sanitize="address"
